"""
ml/db/models.py
New SQLAlchemy ORM models for ML prediction storage.
These are additive — no existing Milestone 1 models are changed.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from datetime import datetime, timezone, date as date_type
from typing import Optional
from sqlalchemy import (
    String, Float, Boolean, Integer, DateTime, Date, Time,
    ForeignKey, Index, Text
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.app.db.session import Base


class MLModelRegistry(Base):
    """Tracks trained ML models and their active versions."""
    __tablename__ = "ml_model_registry"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    model_name: Mapped[str] = mapped_column(String(100), nullable=False)
    model_version: Mapped[str] = mapped_column(String(50), nullable=False)
    task_type: Mapped[str] = mapped_column(String(50), default="classification", nullable=False)
    metrics_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    artifact_path: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    mlflow_run_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    trained_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )

    __table_args__ = (
        Index("idx_ml_registry_active", "model_name", "is_active"),
    )

    def __repr__(self):
        return f"<MLModelRegistry(name={self.model_name!r}, version={self.model_version!r}, active={self.is_active})>"


class IrrigationPrediction(Base):
    """Stores every ML prediction request and its output."""
    __tablename__ = "irrigation_predictions"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    field_id: Mapped[int] = mapped_column(
        ForeignKey("fields.id", ondelete="CASCADE"), nullable=False, index=True
    )
    model_name: Mapped[str] = mapped_column(String(100), nullable=False)
    model_version: Mapped[str] = mapped_column(String(50), default="unknown", nullable=False)
    prediction_timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )
    irrigation_required: Mapped[bool] = mapped_column(Boolean, nullable=False)
    confidence_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    predicted_volume_liters: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    recommended_hour: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    recommended_duration_minutes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    risk_level: Mapped[Optional[str]] = mapped_column(String(20), default="MEDIUM", nullable=True)
    reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    soil_moisture_context: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    temperature_context: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rain_probability_context: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    crop_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    growth_stage: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    schedule_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )

    schedules: Mapped[list["IrrigationSchedule"]] = relationship(
        "IrrigationSchedule", back_populates="prediction", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("idx_predictions_field_time", "field_id", "prediction_timestamp"),
    )

    def __repr__(self):
        return f"<IrrigationPrediction(field={self.field_id}, required={self.irrigation_required}, confidence={self.confidence_score:.2f})>"


class IrrigationSchedule(Base):
    """Time-slotted actionable irrigation schedule generated by the optimizer."""
    __tablename__ = "irrigation_schedules"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    prediction_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("irrigation_predictions.id", ondelete="SET NULL"), nullable=True
    )
    field_id: Mapped[int] = mapped_column(
        ForeignKey("fields.id", ondelete="CASCADE"), nullable=False, index=True
    )
    scheduled_date: Mapped[date_type] = mapped_column(Date, nullable=False)
    recommended_start_time: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    duration_minutes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    volume_liters: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    priority: Mapped[Optional[str]] = mapped_column(String(20), default="MEDIUM", nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )

    prediction: Mapped[Optional["IrrigationPrediction"]] = relationship(
        "IrrigationPrediction", back_populates="schedules"
    )

    __table_args__ = (
        Index("idx_schedules_field_date", "field_id", "scheduled_date"),
    )

    def __repr__(self):
        return f"<IrrigationSchedule(field={self.field_id}, date={self.scheduled_date}, priority={self.priority})>"
